import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FloatButton, Layout, Menu } from "antd";
import { Header, Content, Footer } from "antd/es/layout/layout";
import { WhatsAppOutlined } from "@ant-design/icons";

import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Legal Study",
  description: "Generated by create next app",
};
const items = [
  {
    key: "1",
    label: <Link href="/">Inicio</Link>,
  },
  {
    key: "2",
    label: <Link href="/dashboard">Dashboard</Link>,
  },
  {
    key: "3",
    label: "Item 3",
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Header
            style={{
              position: "sticky",
              top: 0,
              backgroundColor: "white",
              zIndex: 1,
              width: "100%",
              display: "flex",
              alignItems: "center",
            }}
          >
            <div className="demo-logo">CuestasPatinoLogo</div>
            <Menu
              theme="light"
              mode="horizontal"
              defaultSelectedKeys={["1"]}
              style={{ flex: 1, minWidth: 0 }}
              items={items}
            ></Menu>
          </Header>
          <Content>
            {children}
            <FloatButton
              shape="circle"
              type="default"
              // style={{ backgroundColor: "#00b96b" }}
              
              tooltip={<div>Mas informacion</div>}
              icon={<WhatsAppOutlined />}
            />
          </Content>
          <Footer style={{ textAlign: "center" }}>
            CuestasPatino ©2024 Created by Juan Frattin
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
