import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FloatButton, Layout, Menu } from "antd";
import { Header, Content, Footer } from "antd/es/layout/layout";
import { WhatsAppOutlined } from "@ant-design/icons";
import Logos_CuestasPatiño from "../../public/img/Logos_CuestasPatiño_Sinfondo-03.png";
import Image from "next/image";

import "./globals.css";
import './layout.scss';
import Link from "next/link";
import FooterBar from "@/components/footerBar/footerBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Legal Study",
  description: "Generated by create next app",
};
const items = [
  {
    key: "1",
    label: <Link href="/">Inicio</Link>,
  },
  {
    key: "2",
    label: <Link href="/aboutUs">Quienes somos</Link>,
  },
  {
    key: "3",
    label: <Link href="/practiceAreas">Servicios</Link>,
  },
  {
    key: "4",
    label: <Link href="/contact">Contacto</Link>,
  },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
          <Header
            style={{
              position: "sticky",
              top: 0,
              backgroundColor: "white",
              zIndex: 1,
              width: "100%",
              display: "flex",
              alignItems: "center",
              height: 100,
            }}
          >
            <Link href="/">
              <div className="demo-logo">
                <Image
                  alt="logo"
                  width={150}
                  height={150}
                  src={Logos_CuestasPatiño}
                />
              </div>
            </Link>
            <Menu
              theme="light"
              mode="horizontal"
              defaultSelectedKeys={["1"]}
              style={{ flex: 1, minWidth: 0 }}
              items={items}
            ></Menu>
          </Header>
          <Content>
            {children}
            <Link
              href={
                "https://api.whatsapp.com/send?phone=5493517472345&text=Hola,%20en%20qué%20podemos%20ayudarle?"
              }
            >
              <FloatButton
                shape="circle"
                type="default"
                // style={{ backgroundColor: "#00b96b" }}

                tooltip={<div>Mas informacion</div>}
                icon={<WhatsAppOutlined />}
              />
            </Link>
          </Content>
          <Footer style={{ textAlign: "center" }}>
            <FooterBar />
            CuestasPatino ©2024 Created by Juan Frattin
          </Footer>
        </Layout>
      </body>
    </html>
  );
}
